### ISSUE TITLE
Document issue in the flycheck-rtags's config

### ISSUE THREAD

**Issue by BorisJineman** [syamajala/syamajala.github.io#2]
Hi sir,

There may be an issue in flycheck-rtags's config ( only in the document),

---

(require 'flycheck-rtags)

(defun my-flycheck-rtags-setup ()
  (flycheck-select-checker 'rtags)
  (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
  (setq-local flycheck-check-syntax-automatically nil))
;; c-mode-common-hook is also called by c++-mode
## (add-hook 'c-mode-common-hook #'my-flycheck-rtags-setup)'))

is there anything wrong in the last line?
I guess it should be ,,,
(add-hook 'c-mode-common-hook #'my-flycheck-rtags-setup)

Peace and Long Life,
Boris

**Comment by syamajala** [comment]
I think you're right, but I can't seem to find that in my emacs config anywhere. I must have removed it for some reason.
